spring.application.name=expense-reimbursement
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_db
spring.datasource.username=expense_app
spring.datasource.password=expense_app_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=MySuperSecretKeyForExpenseReimbursementSystem123456789
jwt.expiration=86400000

cloudinary.cloud-name=expense_claim
cloudinary.api-key=399747249838934
cloudinary.api-secret=lQF6t1K5-eXHHJK3qpR2XQdbqPg